---
- name: Report AWS applications
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Display AWS application report
      ansible.builtin.debug:
        msg: >-
          {{ query('ansible.builtin.inventory_hostnames', 'all')
           | map('extract', hostvars, 'application_name') 
           | sort
           | unique
           | list }}

