---
- name: Report inventory hosts
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Display inventory report
      ansible.builtin.debug:
        msg: >-
          Inventory Hostname: {{ item }}
          Environment: {{ hostvars[item].environment_name }}
          Region: {{ hostvars[item].region }}
          Application: {{ hostvars[item].application_name }}
      loop: "{{ query('ansible.builtin.inventory_hostnames', 'all') }}"
      when:
        - hostvars[item].backup_enabled
