---
- name: Report inventory hosts
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Display inventory report
      ansible.builtin.debug:
        msg: >-
          Cloud Providers:
          {{ query('ansible.builtin.inventory_hostnames', 'all')
             | map('extract', hostvars, 'cloud')
             | unique
             | sort
             | list }}
